# Generated by Django 4.2.5 on 2023-09-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=256)),
                ('customer_address', models.CharField(max_length=256)),
                ('serial_number', models.CharField(max_length=256)),
                ('accuracy', models.FloatField()),
                ('barometric_pressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('report_type', models.CharField(choices=[('TV', 'Transducer Verify'), ('HC', 'Hardware Calibration')], max_length=256)),
                ('as_found', models.FileField(blank=True, upload_to='')),
                ('as_left', models.FileField(blank=True, upload_to='')),
                ('both', models.FileField(blank=True, upload_to='')),
                ('calibration_cert_id', models.CharField(default=0, max_length=100)),
                ('calibration_date', models.DateField(default=0)),
                ('calibration_due_date', models.DateField(default=0)),
                ('calibration_model', models.CharField(default=0, max_length=100)),
                ('calibration_serial', models.CharField(default=0, max_length=100)),
                ('channel', models.CharField(default=0, max_length=256)),
                ('instrument_model', models.CharField(default=0, max_length=256)),
                ('transducer_model', models.CharField(default=0, max_length=256)),
                ('transducer_span', models.CharField(default=0, max_length=256)),
            ],
        ),
    ]
