# Generated by Django 4.2.3 on 2023-07-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial", models.CharField(max_length=100)),
                ("device", models.CharField(max_length=100)),
                ("calibration_date", models.DateField()),
                ("calibration_due_date", models.DateField()),
            ],
        ),
    ]
