# Generated by Django 4.2.3 on 2023-07-26 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrument", models.CharField(max_length=256)),
                ("customer_name", models.CharField(max_length=256)),
                ("customer_address", models.CharField(max_length=256)),
                ("control_number", models.CharField(max_length=256)),
                ("serial_number", models.CharField(max_length=256)),
                ("accuracy", models.FloatField()),
                ("barometric_pressure", models.FloatField()),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("TV", "Transducer Verify"),
                            ("HC", "Hardware Calibration"),
                        ],
                        max_length=256,
                    ),
                ),
                ("as_found", models.FileField(upload_to="")),
                ("as_left", models.FileField(upload_to="")),
                ("both", models.FileField(upload_to="")),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sheets.configuration",
                    ),
                ),
            ],
        ),
    ]
