# Generated by Django 4.2.5 on 2023-09-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='calibration_cert_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='calibration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='calibration_due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='calibration_model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='calibration_serial',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='channel',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='instrument_model',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='transducer_model',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='transducer_span',
            field=models.CharField(max_length=256),
        ),
    ]
