# Generated by Django 4.2.3 on 2023-07-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0002_sheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheet",
            name="as_found",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="sheet",
            name="as_left",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="sheet",
            name="both",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.RemoveField(
            model_name="sheet",
            name="configuration",
        ),
        migrations.AddField(
            model_name="sheet",
            name="configuration",
            field=models.ManyToManyField(to="sheets.configuration"),
        ),
    ]
