# Generated by Django 4.2.5 on 2023-10-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_remove_sheet_customer_address_sheet_control_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='kind',
            field=models.CharField(blank=True, choices=[('p', 'Pressure Transducer'), ('f', 'Flow Transducer')], max_length=256),
        ),
    ]
