# Generated by Django 4.2.5 on 2023-10-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_sheet_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='kind',
        ),
        migrations.AddField(
            model_name='sheet',
            name='transducer_type',
            field=models.CharField(blank=True, choices=[('Pressure', 'Pressure Transducer'), ('Flow', 'Flow Transducer')], max_length=256),
        ),
    ]
