# Generated by Django 4.2.5 on 2023-10-05 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_remove_sheet_kind_sheet_transducer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='instrument_calibration_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheet',
            name='instrument_calibration_due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
